name: Build Docker image

on:
  pull_request:
    branches: [master]

jobs:
  build_docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        with:
          images: paritytech/trappist

      - name: Build Docker image
        uses: docker/build-push-action@4e4ee680f69700760d5620a94c020aef883043aa #v4.2.0
        with:
          file: docker/trappist-parachain.dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
